# Generated by Django 5.1.1 on 2024-09-12 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField(verbose_name='Data de Pagamento')),
                ('permite_recorrencia', models.BooleanField(default=False, verbose_name='Permitir recorrencia')),
                ('quantidade_recorrencia', models.IntegerField(verbose_name='numero de recorrencias')),
                ('intervalo_recorrencia', models.IntegerField(verbose_name='intervalo em dias entre as recorrências')),
                ('status_recorrencia', models.CharField(max_length=50, verbose_name='Status')),
                ('agencia', models.IntegerField()),
                ('conta', models.IntegerField()),
                ('valor_pagamento', models.IntegerField()),
            ],
        ),
    ]
